-- Run in Snowsight after terraform apply. Role: SECURITYADMIN or ACCOUNTADMIN.

SHOW WAREHOUSES LIKE 'TF_LEARN_WH';
SHOW ROLES LIKE 'TF_LEARN_ANALYST';
SHOW USERS LIKE 'TF_LEARN_ANALYST_SVC';

SHOW GRANTS TO USER TF_LEARN_ANALYST_SVC;
SHOW GRANTS TO ROLE TF_LEARN_ANALYST;
